default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-merge-conflict
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [
            --max-line-length=90,
        ]
        additional_dependencies: [
            flake8-builtins==2.0.1,
            flake8-warnings==0.3.0,
            flake8-simplify==0.19.3,
            flake8-return==1.2.0,
            flake8-comprehensions==3.10.1,
        ]
